version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/demos/sport-shop-angular"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
        group-by: "dependency-name"
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
    cooldown:
      default-days: 7
